#!/bin/bash

# >>> Conda setup <<<
__conda_setup="$('/home/aksu/miniconda3' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    source /home/aksu/miniconda3/etc/profile.d/conda.sh
fi
# <<< End conda setup <<<

conda activate avocado_conda
export PATH=$HOME/miniconda3/cuda/bin:$PATH
export LD_LIBRARY_PATH=$HOME/miniconda3/cuda/lib64:$LD_LIBRARY_PATH
# export THEANO_FLAGS="device=cuda0,floatX=float32,dnn.enabled=True"
export THEANO_FLAGS="device=cuda,floatX=float32,optimizer=fast_run,gpuarray.preallocate=0.8,dnn.enabled=False"
export KERAS_BACKEND=theano

python -u -Wi "$@"
